spring:
  credhub:
    url: https://credhub.service.cf.internal:8844
    oauth2:
      registration-id: credhubtest
  security:
    oauth2:
      client:
        registration:
          credhubtest:
            provider: uaa
            client-id: credhubtest
            client-secret: credhubtest
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: https://uaa.sys.cf.cloud-native.biz/oauth/token/
            